/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [
    require('tailwind-scrollbar'),
    require('tailwind-scrollbar-hide')
],
  mode: "jit",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        text: "var(--text)",
        "text-subtle": "var(--text-subtle)",
        "text-invert": "var(--text-invert)",
        "text-glow-high-contrast": "var(--text-glow-high-contrast)",
        "box-shadow-light": "var(--box-shadow-light)",
        "box-shadow-medium": "var(--box-shadow-medium)",
        "box-shadow-heavy": "var(--box-shadow-heavy)",
        "box-shadow-extra-heavy": "var(--box-shadow-extra-heavy)",
        overlay: "var(--overlay)",
        "overlay-invert": "var(--overlay-invert)",
        "body-background": "var(--body-background)",
        "body-background-accent": "var(--body-background-accent)",
        "body-background-medium": "var(--body-background-medium)",
        "alternate-background": "var(--alternate-background)",
        "alternate-background-medium": "var(--alternate-background-medium)",
        "card-background": "var(--card-background)",
        "border": "var(--border)",
        "border-accent": "var(--border-accent)",
        "border-white-high-contrast": "var(--border-white-high-contrast)",
        "border-yellow-high-contrast": "var(--border-yellow-high-contrast)",
        "table-header": "var(--table-header)",
        "table-row": "var(--table-row)",
        "table-row-header": "var(--table-row-header)",
        "table-border-dark": "var(--table-border-dark)",
        "hover-base": "var(--hover-base)",
        "hover-invert": "var(--hover-invert)",
        "code-header": "var(--code-header)",
        "code-block": "var(--code-block)",
        "control-border": "var(--control-border)",
        "inline-code": "var(--inline-code)",
        "code-highlight-background": "var(--code-highlight-background)",
        "visited": "var(--visited)",
        "score-low-off": "var(--score-low-off)",
        "score-low": "var(--score-low)",
        "score-medium-off": "var(--score-medium-off)",
        "score-medium": "var(--score-medium)",
        "score-high-off": "var(--score-high-off)",
        "score-high": "var(--score-high)",
        "hyperlink": "var(--hyperlink)",
        "primary-base": "var(--primary-base)",
        "primary-background": "var(--primary-background)",
        "primary-background-glow-high-contrast": "var(--primary-background-glow-high-contrast)",
        "primary-dark": "var(--primary-dark)",
        "primary-hover": "var(--primary-hover)",
        "primary-active": "var(--primary-active)",
        "primary-box-shadow": "var(--primary-box-shadow)",
        "primary-invert": "var(--primary-invert)",
        "secondary-base": "var(--secondary-base)",
        "secondary-background": "var(--secondary-background)",
        "secondary-background-glow-high-contrast": "var(--secondary-background-glow-high-contrast)",
        "secondary-dark": "var(--secondary-dark)",
        "secondary-hover": "var(--secondary-hover)",
        "secondary-active": "var(--secondary-active)",
        "secondary-box-shadow": "var(--secondary-box-shadow)",
        'secondary-invert': "var(--secondary-invert)",
        'tertiary-base': "var(--tertiary-base)",
        'tertiary-background': "var(--tertiary-background)",
        'tertiary-background-glow-high-contrast': "var(--tertiary-background-glow-high-contrast)",
        'tertiary-dark': "var(--tertiary-dark)",
        "tertiary-hover": "var(--tertiary-hover)",
        "tertiary-active": "var(--tertiary-active)",
        "tertiary-box-shadow": "var(--tertiary-box-shadow)",
        "tertiary-invert": "var(--tertiary-invert)",
        "success-base": "var(--success-base)",
        "success-background": "var(--success-background)",
        "success-background-glow-high-contrast": "var(--success-background-glow-high-contrast)",
        "success-dark": "var(--success-dark)",
        "success-hover": "var(--success-hover)",
        "success-active": "var(--success-active)",
        "success-box-shadow": "var(--success-box-shadow)",
        "success-invert": "var(--success-invert)",
        "info-base": "var(--info-base)",
        'info-background': "var(--info-background)",
        "info-background-glow-high-contrast": "var(--info-background-glow-high-contrast)",
        'info-dark': "var(--info-dark)",
        'info-hover': "var(--info-hover)",
        'info-active': "var(--info-active)",
        'info-box-shadow': "var(--info-box-shadow)",
        'info-invert': "var(--info-invert)",
        'warning-base': "var(--warning-base)",
        'warning-background': "var(--warning-background)",
        'warning-background-glow-high-contrast': "var(--warning-background-glow-high-contrast)",
        'warning-dark': "var(--warning-dark)",
        'warning-hover': "var(--warning-hover)",
       'warning-active': "var(--warning-active)",
        'warning-box-shadow': "var(--warning-box-shadow)",
        'warning-invert': "var(--warning-invert)",
        'danger-base': "var(--danger-base)",
        'danger-background': "var(--danger-background)",
        'danger-background-glow-high-contrast': "var(--danger-background-glow-high-contrast)",
        'danger-dark': "var(--danger-dark)",
        'danger-hover': "var(--danger-hover)",
       'danger-active': "var(--danger-active)",
        'danger-box-shadow': "var(--danger-box-shadow)",
        "danger-invert": "var(--danger-invert)",
        "facepile-red": "var(--facepile-red)",
        "facepile-teal": "var(--facepile-teal)",
        "facepile-blue": "var(--facepile-blue)",
        "gradient-text-purple": "var(--gradient-text-purple)",
        "gradient-text-blue": "var(--gradient-text-blue)",
        primary: "#050816",
        secondary: "#aaa6c3",
        tertiary: "#151030",
        "black-100": "#100d25",
        "black-200": "#090325",
        "white-100": "#f3f3f3",
      },
      boxShadow: {
        card: "0px 35px 120px -15px #211e35",
      },
      screens: {
        xs: "450px",
      },
  },
  plugins: [],
}}
